#!/usr/bin/env ruby
# frozen_string_literal: true

require "suiren"
require "optparse"

Suiren::Suiren.init_i18n

opt = OptionParser.new
bind_addr = "localhost"
port = 8080
content = String.new

opt.on("-V", "--version", I18n.t("version_info")) do |_v|
  puts("#{File.basename($PROGRAM_NAME)} (#{Suiren::VERSION})")
  exit(true)
end

opt.on("--license", I18n.t("license_info")) do |_v|
  puts(Suiren::COPYRIGHT)
  exit(true)
end

opt.on("--bind-address [Bind Address]", I18n.t("bind_addr")) do |addr|
  bind_addr = addr
end

opt.on("-p [Port]", "--port", I18n.t("port")) do |p|
  port = p.to_i
end

opt.on("-c [Content]", "--content", I18n.t("content")) do |cont|
  content = cont
end

begin
  opt.parse!(ARGV)
rescue OptionParser::InvalidOption
  warn(I18n.t("option_not_appropriate"))
  exit(false)
end

Suiren::Suiren.new(bind_addr, port, content: content)
